# Generated by Django 3.2.3 on 2023-07-13 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_recept', models.CharField(help_text='Придумайте название рецепта', max_length=200, unique=True, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='recepts/', verbose_name='Фото рецепта')),
                ('text_description', models.TextField(help_text='Опишите детально рецепт', verbose_name='Подробное описание рецепта')),
                ('time_cooking', models.PositiveIntegerField(help_text='Укажите время приготовления в минутах', verbose_name='Время приготовления в минутах')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepts', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
            ],
        ),
    ]
