# Generated by Django 3.2.3 on 2023-07-28 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopper', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='recept',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepts', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AddField(
            model_name='recept',
            name='ingredients',
            field=models.ManyToManyField(help_text='Выберите ингридиенты для рецепта', related_name='recepts', through='recepts.IngridientAmount', to='recepts.Ingredients', verbose_name='Ингридиенты'),
        ),
        migrations.AddField(
            model_name='recept',
            name='tags',
            field=models.ManyToManyField(to='recepts.Tag', verbose_name='Тэг'),
        ),
        migrations.AddField(
            model_name='ingridientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.ingredients', verbose_name='Ингридиент'),
        ),
        migrations.AddField(
            model_name='ingridientamount',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recepts.recept', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='ingredients',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='recepts.recept', verbose_name='Рецепт'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('user', 'recept'), name='unique_shopping_list'),
        ),
        migrations.AddConstraint(
            model_name='ingridientamount',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recept'), name='ingredient_in_recept'),
        ),
        migrations.AddConstraint(
            model_name='favourites',
            constraint=models.UniqueConstraint(fields=('user', 'recept'), name='unique_favourites'),
        ),
    ]
