# Generated by Django 3.2.3 on 2023-07-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0003_auto_20230715_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='recepts.recept', verbose_name='Рецепт'),
        ),
    ]
