# Generated by Django 3.2.3 on 2023-07-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0003_auto_20230715_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recept',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='time_cooking',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='name_recept',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='text_description',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='favourites',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='recepts.recept', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopper', to='recepts.recept', verbose_name='Рецепт'),
        ),
    ]
