# Generated by Django 3.2.3 on 2023-07-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0004_alter_favourites_recept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopper', to='recepts.recept', verbose_name='Рецепт'),
        ),
    ]
