# Generated by Django 3.2.3 on 2023-07-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepts', '0005_alter_shoppinglist_recept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recept',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='time_cooking',
            new_name='cooking_time',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='name_recept',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='recept',
            old_name='text_description',
            new_name='text',
        ),
    ]
