# Generated by Django 3.2.3 on 2023-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230713_1429'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user'),
        ),
    ]
